# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1f455479062f3eeb165b81a239db314201e66396a0e5be90eacb56e539ea96710bf54d6a1ec4b15ff51dcc7005a5d3ab779df0a87256549462bd2a0cadf1961

test:
  secret_key_base: ea68b0c9cc4dd5043c823777b17ed75a757d0816797c8ad7a30e0aeeb557ef446e24c9a15d309c4083a302d60e16023a0b07baf221b21d49408ad92e52c2c942

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
